---

- name: Comice Control center | Install dependencies
  become: yes
  apt:
    name:
      - python3
      - python3-dbus
      - util-linux
      - gsettings-desktop-schemas
      - wireless-tools
      - iproute2
      - alsa-utils

- name: Comice Control center | Clone git repository
  git:
    repo: "{{ comice_control_git }}"
    dest: "{{ home_directory }}/Downloads/comice-control-center"

- name: Comice Control center | Install pip dependencies
  shell:
    cmd: "cd {{ home_directory }}/Downloads/comice-control-center && pip3 install -r requirements.txt"

- name: Comice Control center | Add Launcher - plugin-31
  xfconf:
    channel: xfce4-panel
    property: /plugins/plugin-31
    value_type: string
    value: launcher

- name: Comice Control center | Modify Launcher - plugin-31
  xfconf:
    channel: xfce4-panel
    property: /plugins/plugin-31/items
    value_type: string
    value: "comice-control-center.desktop"
    force_array: yes

- name: Comice Control center | Make sure ~/.config/xfce4/panel/launcher-31 exists
  file:
    path: "{{ home_directory }}/.config/xfce4/panel/launcher-31"
    state: directory

- name: Comice Control center | Add comice-control-center.desktop
  template:
    src: comice-control-center.desktop
    dest: "{{ home_directory }}/.config/xfce4/panel/launcher-31/comice-control-center.desktop"

- name: Comice Control center | Add separator - plugin-32
  xfconf:
    channel: xfce4-panel
    property: /plugins/plugin-32
    value_type: string
    value: separator

- name: Comice Control center | Modify separator - plugin-32
  xfconf:
    channel: xfce4-panel
    property: /plugins/plugin-32/style
    value_type: uint
    value: 0

- name: Xfce Panel | Rearrange Plugins
  xfconf:
    channel: xfce4-panel
    property: /panels/panel-1/plugin-ids
    value_type: int
    value: [26,1,3,30,5,29,28,6,7,8,9,10,32,31,11,12,13,14,27]
